-- Run this in Supabase SQL Editor (Database -> SQL Editor -> New Query)

create table chatearn_registrations (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text not null,
  created_at timestamp with time zone default now()
);

create table chatearn_withdrawals (
  id bigint generated by default as identity primary key,
  account_name text not null,
  account_number text not null,
  bank text not null,
  amount numeric not null,
  user_email text,
  created_at timestamp with time zone default now()
);

-- Enable insert access for anonymous users (since this is a public-facing funnel)
alter table chatearn_registrations enable row level security;
alter table chatearn_withdrawals enable row level security;

create policy "Allow public insert" on chatearn_registrations
  for insert to anon with check (true);

create policy "Allow public insert" on chatearn_withdrawals
  for insert to anon with check (true);
